#!/usr/bin/env python3
import argparse
from urllib.parse import urlparse
import subprocess


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("cookie_file_name")
    parser.add_argument("http_tested_address")
    args = parser.parse_args()
    return args


def run_http():
    netloc = url.netloc
    if url.port is None:
        netloc += ":80"

    # TODO zmien sciezke z cmake.../ na ./
    subprocess.run(["cmake-build-debug/testhttp_raw", netloc, args.cookie_file_name, args.http_tested_address])


def run_https():
    pass


args = parse_arguments()
url = urlparse(args.http_tested_address)

if url.scheme == "http":
    run_http()
elif url.scheme == "https":
    run_https()
else:
    pass # error

